; picoSun installer — portable app folder -> user-local install
; Run: makensis.exe picoSun.nsi
!define APP "picoSun"
!define VER "1.0.5"
!define PUB "Nim4a"

Name "${APP}"
OutFile "picoSun-setup-${VER}.exe"
Icon "..\picoSun.ico"
UninstallIcon "..\picoSun.ico"
InstallDir "$LOCALAPPDATA\Programs\picoSun"
RequestExecutionLevel user
Unicode true
SetCompressor lzma
CRCCheck on
XPStyle on

!include "MUI2.nsh"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

Section "Install"
  SetOutPath "$INSTDIR"
  # A fresh install is a fresh start: drop the saved window state so the app
  # comes up fullscreen on first launch instead of inheriting a windowed
  # geometry from an older build (the setting lives beside the app's own key).
  DeleteRegKey HKCU "Software\picoSun\picoSun"
  File /r "..\dist\picoSun\*.*"
  File /r "..\picoSun.ico"
  # per-format icon pack: app icon + one doc icon per family
  File /r "..\icons\*.ico"
  WriteUninstaller "$INSTDIR\uninstall.exe"
  SetOutPath "$INSTDIR"
  # launcher scr
  FileOpen $0 "$INSTDIR\run.cmd" w
  FileWrite $0 "@echo off$\r$\n"
  FileWrite $0 '"$INSTDIR\picoSun.exe" %*$\r$\n'
  FileClose $0
  # desktop shortcut (with icon)
  CreateShortCut "$DESKTOP\picoSun.lnk" "$INSTDIR\picoSun.exe" "" "$INSTDIR\picoSun.ico"
  # start menu shortcut
  CreateDirectory "$SMPROGRAMS\picoSun"
  CreateShortCut "$SMPROGRAMS\picoSun\picoSun.lnk" "$INSTDIR\picoSun.exe" "" "$INSTDIR\picoSun.ico"
  CreateShortCut "$SMPROGRAMS\picoSun\Uninstall.lnk" "$INSTDIR\uninstall.exe"
  # registry: silent
  WriteRegStr HKCU "Software\picoSun" "InstallDir" "$INSTDIR"
  # file associations (user-level, reversible): photos -> photo icon,
  # RAW -> raw icon, HDR -> hdr icon, animations -> anim icon. picoSun is
  # registered as OpenWith for everything, default for nothing -- the user
  # picks it in "Open with", we never hijack their defaults.
  WriteRegStr HKCU "Software\Classes\picoSun.photo\DefaultIcon" "" "$INSTDIR\icon_photo.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun.photo\shell\open\command" "" '"$INSTDIR\picoSun.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun.raw\DefaultIcon" "" "$INSTDIR\icon_raw.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun.raw\shell\open\command" "" '"$INSTDIR\picoSun.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun.hdr\DefaultIcon" "" "$INSTDIR\icon_hdr.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun.hdr\shell\open\command" "" '"$INSTDIR\picoSun.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\picoSun.anim\DefaultIcon" "" "$INSTDIR\icon_anim.ico,0"
  WriteRegStr HKCU "Software\Classes\picoSun.anim\shell\open\command" "" '"$INSTDIR\picoSun.exe" "%1"'
  WriteRegStr HKCU "Software\Classes\.avif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.bmp\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.cur\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.cut\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.dds\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.dib\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.emf\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.exif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.fax\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.flif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.hdp\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.heic\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.heif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.hif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.ico\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.j2k\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jfif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jp2\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpe\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpeg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jpg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jxl\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.jxr\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mjpeg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.pbm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.pcx\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.pgm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.png\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.pnm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.ppm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.psb\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.psd\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.qoi\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.svg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.svgz\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.tga\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.tif\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.tiff\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.viff\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.wbm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.wdp\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.wmf\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.wpg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.xbm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.xpm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.xv\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.3fr\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.ari\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.arq\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.arw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.bay\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.cap\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.cr2\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.cr3\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.crw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.dcr\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.dcs\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.dng\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.drf\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.eip\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.erf\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.fff\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.gpr\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.iiq\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.k25\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.kdc\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.mdc\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.mef\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.mos\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.mrw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.nef\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.nrw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.obm\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.orf\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.pef\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.ptx\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.pxn\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.r3d\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.raf\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.raw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.rw2\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.rwl\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.rwz\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.sr2\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.srf\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.srw\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.x3f\OpenWithProgids" "picoSun.raw" ""
  WriteRegStr HKCU "Software\Classes\.exr\OpenWithProgids" "picoSun.hdr" ""
  WriteRegStr HKCU "Software\Classes\.fits\OpenWithProgids" "picoSun.hdr" ""
  WriteRegStr HKCU "Software\Classes\.hdr\OpenWithProgids" "picoSun.hdr" ""
  WriteRegStr HKCU "Software\Classes\.pfm\OpenWithProgids" "picoSun.hdr" ""
  WriteRegStr HKCU "Software\Classes\.ani\OpenWithProgids" "picoSun.anim" ""
  WriteRegStr HKCU "Software\Classes\.apng\OpenWithProgids" "picoSun.anim" ""
  WriteRegStr HKCU "Software\Classes\.gif\OpenWithProgids" "picoSun.anim" ""
  WriteRegStr HKCU "Software\Classes\.gifv\OpenWithProgids" "picoSun.anim" ""
  WriteRegStr HKCU "Software\Classes\.webp\OpenWithProgids" "picoSun.anim" ""
  WriteRegStr HKCU "Software\Classes\.avi\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.flv\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.m2ts\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.m4v\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mkv\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mov\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mp4\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mpeg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mpg\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.mts\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.ogv\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.rmvb\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.ts\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.webm\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\.wmv\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\Classes\3gp\OpenWithProgids" "picoSun.photo" ""
  WriteRegStr HKCU "Software\picoSun" "AssocVer" "1"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun" "DisplayName" "picoSun ${VER}"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun" "Publisher" "${PUB}"
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\run.cmd"
  RMDir /r "$INSTDIR"
  Delete "$DESKTOP\picoSun.lnk"
  RMDir /r "$SMPROGRAMS\picoSun"
  DeleteRegKey HKCU "Software\picoSun"
  DeleteRegValue HKCU "Software\Classes\.avif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.bmp\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.cur\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.cut\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.dds\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.dib\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.emf\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.exif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.fax\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.flif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.hdp\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.heic\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.heif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.hif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.ico\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.j2k\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jfif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jp2\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jpe\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jpeg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jpg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jxl\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.jxr\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mjpeg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.pbm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.pcx\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.pgm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.png\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.pnm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.ppm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.psb\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.psd\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.qoi\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.svg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.svgz\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.tga\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.tif\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.tiff\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.viff\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.wbm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.wdp\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.wmf\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.wpg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.xbm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.xpm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.xv\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.3fr\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.ari\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.arq\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.arw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.bay\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.cap\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.cr2\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.cr3\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.crw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.dcr\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.dcs\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.dng\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.drf\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.eip\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.erf\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.fff\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.gpr\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.iiq\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.k25\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.kdc\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.mdc\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.mef\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.mos\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.mrw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.nef\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.nrw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.obm\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.orf\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.pef\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.ptx\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.pxn\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.r3d\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.raf\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.raw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.rw2\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.rwl\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.rwz\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.sr2\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.srf\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.srw\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.x3f\OpenWithProgids" "picoSun.raw"
  DeleteRegValue HKCU "Software\Classes\.exr\OpenWithProgids" "picoSun.hdr"
  DeleteRegValue HKCU "Software\Classes\.fits\OpenWithProgids" "picoSun.hdr"
  DeleteRegValue HKCU "Software\Classes\.hdr\OpenWithProgids" "picoSun.hdr"
  DeleteRegValue HKCU "Software\Classes\.pfm\OpenWithProgids" "picoSun.hdr"
  DeleteRegValue HKCU "Software\Classes\.ani\OpenWithProgids" "picoSun.anim"
  DeleteRegValue HKCU "Software\Classes\.apng\OpenWithProgids" "picoSun.anim"
  DeleteRegValue HKCU "Software\Classes\.gif\OpenWithProgids" "picoSun.anim"
  DeleteRegValue HKCU "Software\Classes\.gifv\OpenWithProgids" "picoSun.anim"
  DeleteRegValue HKCU "Software\Classes\.webp\OpenWithProgids" "picoSun.anim"
  DeleteRegValue HKCU "Software\Classes\.avi\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.flv\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.m2ts\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.m4v\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mkv\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mov\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mp4\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mpeg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mpg\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.mts\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.ogv\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.rmvb\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.ts\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.webm\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\.wmv\OpenWithProgids" "picoSun.photo"
  DeleteRegValue HKCU "Software\Classes\3gp\OpenWithProgids" "picoSun.photo"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\picoSun"
SectionEnd